# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test <- function(arg) {
    .Call(`_pokeRmc_test`, arg)
}

#' Calculate pre-flop probability estimates
#' 
#' @param your_cards your cards as a length-4 character vector.
#' @param num_sims number of simulations.
#' @param num_folders number of folders.
#' @param num_oppo number of opponents.
#' @return a character vector
#' @export
preFlopComp <- function(your_cards, num_sims, num_folders, num_oppo) {
    .Call(`_pokeRmc_preFlopComp`, your_cards, num_sims, num_folders, num_oppo)
}

#' Calculate pre-turn probability estimates
#' 
#' @param your_cards your cards as a length-4 character vector.
#' @param num_sims number of simulations.
#' @param num_folders number of folders.
#' @param num_oppo number of opponents.
#' @param comm_cards community cards.
#' @export
preTurnComp <- function(your_cards, num_sims, num_folders, num_oppo, comm_cards) {
    .Call(`_pokeRmc_preTurnComp`, your_cards, num_sims, num_folders, num_oppo, comm_cards)
}

#' Calculate pre-river probability estimates
#' 
#' @param your_cards your cards as a length-4 character vector.
#' @param num_sims number of simulations.
#' @param num_folders number of folders.
#' @param num_oppo number of opponents.
#' @param comm_cards community cards.
#' @export
preRiverComp <- function(your_cards, num_sims, num_folders, num_oppo, comm_cards) {
    .Call(`_pokeRmc_preRiverComp`, your_cards, num_sims, num_folders, num_oppo, comm_cards)
}

#' Calculate post-river probability estimates
#' 
#' @param your_cards your cards as a length-4 character vector.
#' @param num_sims number of simulations.
#' @param num_folders number of folders.
#' @param num_oppo number of opponents.
#' @param comm_cards community cards.
#' @export
postRiverComp <- function(your_cards, num_sims, num_folders, num_oppo, comm_cards) {
    .Call(`_pokeRmc_postRiverComp`, your_cards, num_sims, num_folders, num_oppo, comm_cards)
}

